### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by Vad1mo** [mssola/cconfig#3]
I am not sure but I thing this error I see now in Portus has something to do with cconfig. However I can't figure out what exactly it is. 

**Error**
undefined method `[]' for nil:NilClass

```
/portus # rake -v assets:environment 
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/cconfig-1.1.0/lib/cconfig/hash_utils.rb:36:in `enabled?'
/portus/config/initializers/devise.rb:238:in `block in <top (required)>'
/usr/local/bundle/gems/devise-3.5.1/lib/devise.rb:281:in `setup'
/portus/config/initializers/devise.rb:4:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/portus/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)

```

**Comment by Vad1mo** [comment]
ok I got it.
The line 238 in  `/portus/config/initializers/devise.rb:238:in `block in <top (required)>'` is `if APP_CONFIG.enabled? "oauth.google_oauth2"` however, I didn't had oauth in the base config yet. 

after adding it to the config.yml it started to work. 
 
Not sure if a better error message could indicate what exactly isn't working.

**Comment by mssola** [comment]
@Vad1mo PR #4 should fix this issue. From now on it will simply return false, which is the expected returned value.
